listas vs arrays

In [1]:
lista = [2,6,8, 'Hola Mundo']
lista[3]

'Hola Mundo'

In [2]:
matriz = [[1,2,3],
          [4,5,6],
          [7,8,9]]
#matriz[2][1]
matriz * 4

[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]

In [2]:
import numpy as np

In [4]:
numeros = [3,45,6]
a = np.array(numeros)
print(type(a))

<class 'numpy.ndarray'>


In [5]:
lista = [2,6,8]
b = np.array(lista)
print(b)

[2 6 8]


In [6]:
b * 4

array([ 8, 24, 32])

In [19]:
#secuencia = np.arange(3,25)
impares = np.arange(1,34,2)
impares


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [22]:
secuencia = np.linspace(2, 8, 20, dtype=float)
secuencia

array([2.        , 2.31578947, 2.63157895, 2.94736842, 3.26315789,
       3.57894737, 3.89473684, 4.21052632, 4.52631579, 4.84210526,
       5.15789474, 5.47368421, 5.78947368, 6.10526316, 6.42105263,
       6.73684211, 7.05263158, 7.36842105, 7.68421053, 8.        ])

In [24]:
ceros = np.zeros((3,5), dtype=float)
ceros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
cincos = np.full((4,6), 0)
cincos ** 2

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [28]:
print(np.full_like(cincos, np.pi, dtype=float))

[[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]]


In [3]:
#Módulo random
azar = np.random.rand(5,3)
azar * 10

array([[8.86246984, 0.40222713, 4.27918983],
       [1.94319581, 6.66323821, 9.63839561],
       [0.25494163, 9.69853961, 5.9143425 ],
       [6.80248058, 9.01556913, 2.15324013],
       [9.68701388, 7.55428708, 5.36683353]])

In [4]:
azar = np.random.randint(1, 19, (4,5))
azar

array([[ 3, 15, 12,  5,  6],
       [14, 11, 13, 13, 15],
       [12,  6, 16, 10, 13],
       [18, 12,  9, 16,  8]])

In [7]:
#Atributos
print(type(azar.shape))
print(azar.dtype)

<class 'tuple'>
int64


In [8]:
azar2 = np.reshape(azar, (5,2,2))
azar2

array([[[ 3, 15],
        [12,  5]],

       [[ 6, 14],
        [11, 13]],

       [[13, 15],
        [12,  6]],

       [[16, 10],
        [13, 18]],

       [[12,  9],
        [16,  8]]])

In [9]:
azar.T

array([[ 3, 14, 12, 18],
       [15, 11,  6, 12],
       [12, 13, 16,  9],
       [ 5, 13, 10, 16],
       [ 6, 15, 13,  8]])

In [12]:
print(azar)
print(azar[1,2])
#se saca toda la columna 02
print(azar[:,2])
#toda la fila 2
print(azar[2, :])
print(azar[1:3, 1:3])

[[ 3 15 12  5  6]
 [14 11 13 13 15]
 [12  6 16 10 13]
 [18 12  9 16  8]]
13
[12 13 16  9]
[12  6 16 10 13]
[[11 13]
 [ 6 16]]


In [13]:
promedio = np.mean(azar)
promedio

11.35

In [14]:
mascara = (azar % 2 == 0) & (azar > 10)
azar[mascara]


array([12, 14, 12, 16, 18, 12, 16])