listas vs arrays

In [ ]:
lista = [2,6,8, 'Hola Mundo']
lista[3]

In [ ]:
matriz = [[1,2,3],
          [4,5,6],
          [7,8,9]]
#matriz[2][1]
matriz * 4

In [ ]:
import numpy as np

In [ ]:
numeros = [3,45,6]
a = np.array(numeros)
print(type(a))

In [ ]:
lista = [2,6,8]
b = np.array(lista)
print(b)

In [ ]:
b * 4

In [ ]:
#secuencia = np.arange(3,25)
impares = np.arange(1,34,2)
impares

In [ ]:
secuencia = np.linspace(2, 8, 4, dtype=int)
secuencia

In [ ]:
ceros = np.zeros((3,5), dtype=int)
ceros

In [ ]:
cincos = np.full((4,4), 5)
cincos ** 2

In [ ]:
print(np.full_like(cincos, np.pi, dtype=float))

In [ ]:
#Módulo random
azar = np.random.rand(5,3)
azar * 10

In [70]:
azar = np.random.randint(1, 19, (4,5))
azar

array([[ 5,  5,  2,  9, 18],
       [ 9,  7,  6, 11,  4],
       [ 2,  8,  1,  7, 12],
       [ 5,  2,  4, 12, 18]])

In [ ]:
#Atributos
azar.shape
azar.dtype

In [ ]:
azar2 = np.reshape(azar, (5,2,2))
azar2

In [ ]:
azar.T

In [75]:
azar[1,2]
azar[:,2]
azar[2, :]
azar[1:3, 1:3]

array([[7, 6],
       [8, 1]])

In [77]:
promedio = np.mean(azar)
promedio

7.35

In [84]:
mascara = (azar % 2 == 0) & (azar > 10)
azar[mascara]


array([18, 12, 12, 18])